const fs=require('fs');const {chromium}=require('playwright');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({viewport:{width:390,height:844}});
await page.route('https://mayfly.test/**',route=>route.fulfill({contentType:route.request().url().endsWith('.js')?'text/javascript':'text/html',body:route.request().url().endsWith('.js')?fs.readFileSync('chat-commands.js','utf8'):'<head></head><body><div class="chatbody">Hello</div><input class="tinput"><button>Send</button></body>'}));
await page.goto('https://mayfly.test/');
await page.evaluate(async()=>{const m=await import('./chat-commands.js');m.saveFont('font-family: Georgia; font-size: 20px; font-weight: 500;');if(getComputedStyle(document.querySelector('.chatbody')).fontSize!=='20px')throw Error('Font not applied');if(!localStorage.getItem(m.FONT_KEY))throw Error('Font not saved');if(getComputedStyle(document.querySelector('button')).fontSize==='20px')throw Error('Controls styled');});
await page.reload();await page.evaluate(async()=>{const m=await import('./chat-commands.js');m.applySavedFont();if(getComputedStyle(document.querySelector('.chatbody')).fontSize!=='20px')throw Error('Font not restored');
for(const css of ['position:fixed;','font-family: url(https://bad.test/font);','font-size: nonsense;','font-size:20px; font-size: nonsense;','font-family: serif; } body {display:none','font-size:20px !important']){let rejected=false;try{m.saveFont(css);}catch{rejected=true;}if(!rejected)throw Error('Invalid CSS accepted: '+css);}
if(getComputedStyle(document.querySelector('.chatbody')).fontSize!=='20px')throw Error('Invalid CSS overwrote saved preference');m.saveFont('reset');if(localStorage.getItem(m.FONT_KEY)!==null||document.getElementById('chat-font-preference').textContent)throw Error('Reset failed');});
console.log('Font persistence, reset, and CSS validation passed');await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
