import {test} from 'node:test';import assert from 'node:assert/strict';import {downloadChunkedRelay,RESUMABLE_THRESHOLD,RESUMABLE_CHUNK,resumableUpload,uploadChunkedRelay,uploadRelay} from '../storage-upload.js';
const response=(status,headers={},body='')=>({ok:status>=200&&status<300,status,headers:{get:key=>headers[key.toLowerCase()]??null},text:async()=>body});
test('large upload uses 6 MB TUS chunks and reports progress',async()=>{const size=RESUMABLE_CHUNK*2+123,calls=[],progress=[];let offset=0;await resumableUpload({projectUrl:'https://abc.supabase.co',publishableKey:'key',accessToken:'token',bucket:'mf-snaps',path:'id',blob:new Blob([new Uint8Array(size)]),onProgress:(a,b)=>progress.push([a,b]),fetcher:async(url,init)=>{calls.push({url,init,size:init.body?.size});if(init.method==='POST')return response(201,{location:'/upload/1','upload-offset':'0'});offset+=init.body.size;return response(204,{'upload-offset':String(offset)});}});assert.equal(calls[0].url,'https://abc.storage.supabase.co/storage/v1/upload/resumable');assert.deepEqual(calls.slice(1).map(c=>c.size),[RESUMABLE_CHUNK,RESUMABLE_CHUNK,123]);assert.deepEqual(progress.at(-1),[size,size]);assert.match(calls[0].init.headers['upload-metadata'],/bucketName/);});
test('transient PATCH failure retries the same offset',async()=>{let patches=0;await resumableUpload({projectUrl:'https://abc.supabase.co',publishableKey:'key',accessToken:'token',bucket:'b',path:'p',blob:new Blob([new Uint8Array(10)]),fetcher:async(url,init)=>init.method==='POST'?response(201,{location:'/u'}):++patches===1?response(500):response(204,{'upload-offset':'10'})});assert.equal(patches,2);});
test('413 reports the configured Storage limit',async()=>{await assert.rejects(resumableUpload({projectUrl:'https://abc.supabase.co',publishableKey:'key',accessToken:'token',bucket:'b',path:'p',blob:new Blob([new Uint8Array(10)]),fetcher:async()=>response(413,{},'too large')}),/Storage file-size limit/);});
test('small payload keeps standard upload and large payload requires session',async()=>{let standards=0;const sb={storage:{from:()=>({upload:async()=>{standards++;return {error:null};}})},auth:{getSession:async()=>({data:{session:null}})}};assert.equal((await uploadRelay({sb,projectUrl:'x',publishableKey:'k',bucket:'b',path:'p',body:new Blob([new Uint8Array(RESUMABLE_THRESHOLD)])})).error,null);assert.equal(standards,1);assert.match((await uploadRelay({sb,projectUrl:'x',publishableKey:'k',bucket:'b',path:'p',body:new Blob([new Uint8Array(RESUMABLE_THRESHOLD+1)])})).error.message,/session expired/);});

test('lost PATCH response resumes from server offset without duplicating bytes',async()=>{let patches=0,head=0;await resumableUpload({projectUrl:'https://abc.supabase.co',publishableKey:'key',accessToken:'token',bucket:'b',path:'p',blob:new Blob([new Uint8Array(10)]),fetcher:async(url,init)=>{if(init.method==='POST')return response(201,{location:'/u'});if(init.method==='PATCH'){patches++;throw Error('response lost');}head++;return response(200,{'upload-offset':'10'});}});assert.equal(patches,1);assert.equal(head,1);});

test('native Blob history avoids base64 expansion and survives structured cloning',()=>{const source=new Blob([new Uint8Array(1024*1024)],{type:'video/mp4'});const entry=structuredClone({kind:'media',data:source});assert.ok(entry.data instanceof Blob);assert.equal(entry.data.size,source.size);assert.equal(entry.data.type,'video/mp4');});

test('chunked upload encrypts on demand and retries without advancing the source chunk',async()=>{const calls=[],encrypted=[new Uint8Array(6),new Uint8Array(4)],progress=[];let offset=0,failed=false;const encryptor={encryptedSize:10,chunkCount:2,chunkSize:4,plainSize:6,encryptChunk:async index=>{calls.push(index);return encrypted[index].buffer;}};await uploadChunkedRelay({projectUrl:'https://abc.supabase.co',publishableKey:'key',accessToken:'token',bucket:'b',path:'p',encryptor,onProgress:(a,b)=>progress.push([a,b]),fetcher:async(url,init)=>{if(init.method==='POST')return response(201,{location:'/u','upload-offset':'0'});if(init.method==='HEAD')return response(200,{'upload-offset':String(offset)});if(!failed){failed=true;return response(500);}offset+=init.body.byteLength;return response(204,{'upload-offset':String(offset)});}});assert.deepEqual(calls,[0,1]);assert.deepEqual(progress,[[4,6],[6,6]]);});

test('chunked download requests exact ranges and assembles plaintext in order',async()=>{const ranges=[],plain=[new Uint8Array([1,2,3]),new Uint8Array([4,5])];const blob=await downloadChunkedRelay({url:'https://files.test/x',plainSize:5,chunkSize:3,mime:'video/mp4',decryptChunk:async(index,encrypted)=>{assert.equal(encrypted.byteLength,plain[index].byteLength+16);return plain[index].buffer;},fetcher:async(url,init)=>{ranges.push(init.headers.Range);const index=ranges.length-1;return {...response(206),arrayBuffer:async()=>new Uint8Array(plain[index].byteLength+16).buffer};}});assert.deepEqual(ranges,['bytes=0-18','bytes=19-36']);assert.deepEqual(new Uint8Array(await blob.arrayBuffer()),new Uint8Array([1,2,3,4,5]));assert.equal(blob.type,'video/mp4');});
