const fs=require('fs');const {chromium}=require('playwright');
(async()=>{const browser=await chromium.launch({headless:true,args:['--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream']});const page=await browser.newPage();page.on('console',m=>console.log(m.text()));
const core=fs.readFileSync('core.js','utf8'),start=core.indexOf('const processVideo ='),end=core.indexOf('// Avatars are small',start);
await page.route('https://mayfly.test/**',route=>{let name=new URL(route.request().url()).pathname.slice(1),body='<canvas id="canvas" width="320" height="240"></canvas>',contentType='text/html';if(name==='video-media.js'){body=fs.readFileSync(name,'utf8').replace("video.muted=true;","video.addEventListener('loadedmetadata',()=>console.log('metadata',video.readyState,video.videoWidth));video.addEventListener('loadeddata',()=>console.log('data',video.readyState,video.videoWidth));video.muted=true;").replace("video.pause();return","console.log('Decoded frame',video.readyState,video.duration);video.pause();return");contentType='text/javascript';}if(name==='prepare.js'){body=`import {loadVideoBlob,waitForVideo} from './video-media.js';const PREVIEW_PX=24;const scaleTo=(v)=>{const c=document.createElement('canvas');c.width=24;c.height=18;c.getContext('2d').drawImage(v,0,0,24,18);return c;};const encodePreview=c=>c.toDataURL('image/jpeg');${core.slice(start,end)} export {processVideo};`;contentType='text/javascript';}route.fulfill({body,contentType});});
await page.goto('https://mayfly.test/');const result=await page.evaluate(async()=>{
const {recordingOptions,loadVideoBlob}=await import('./video-media.js'),{processVideo}=await import('./prepare.js');let runs=[];
for(const forced of ['video/webm;codecs=vp8',null]){if(forced&&!MediaRecorder.isTypeSupported(forced))continue;const c=document.getElementById('canvas'),ctx=c.getContext('2d'),stream=await navigator.mediaDevices.getUserMedia({video:true,audio:true}),rec=new MediaRecorder(stream,forced?{mimeType:forced}:recordingOptions()),chunks=[];rec.ondataavailable=e=>chunks.push(e.data);const stopped=new Promise(resolve=>rec.onstop=resolve);const interval=setInterval(()=>{ctx.fillStyle=`hsl(${Date.now()%360},80%,50%)`;ctx.fillRect(0,0,320,240);},30);rec.start(100);await new Promise(r=>setTimeout(r,1500));rec.stop();await stopped;clearInterval(interval);stream.getTracks().forEach(t=>t.stop());const blob=new Blob(chunks,{type:rec.mimeType});
console.log('Recording',rec.mimeType,blob.size);for(let i=0;i<3;i++){console.log('Preparing',i);const shot=await processVideo(blob);if(!shot.w||!shot.h||shot.rawBlob.size!==blob.size)throw Error('Preparation failed');URL.revokeObjectURL(shot.localPreviewUrl);}
// Simulate the encrypted relay payload's byte round trip before decoding.
const key=await crypto.subtle.generateKey({name:'AES-GCM',length:256},true,['encrypt','decrypt']),iv=crypto.getRandomValues(new Uint8Array(12)),encrypted=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,await blob.arrayBuffer()),plain=await crypto.subtle.decrypt({name:'AES-GCM',iv},key,encrypted);console.log('Roundtrip decoding');const decoded=await loadVideoBlob(new Blob([plain],{type:blob.type}));decoded.release();runs.push({mime:rec.mimeType,bytes:blob.size});}
let rejected=false;try{await loadVideoBlob(new Blob(['invalid'],{type:'video/mp4'}));}catch{rejected=true;}if(!rejected)throw Error('Corrupt video accepted');return runs;});console.log('Real recording, repeated preparation, encrypted round trip and corrupt video checks passed',result);await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
